dist: trusty
language: cpp
compiler: g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - g++-6
      - gcc-6

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.29.1/bazel_0.29.1-linux-x86_64.deb
  - sha256sum -c utils/bazel_0.29.1-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.29.1-linux-x86_64.deb

script:
  - g++ --version
  - gcc --version
  - ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - g++ --version
  - gcc --version
  - which g++
  - which gcc
  - bazel build -s --sandbox_debug --verbose_failures -c opt //benchmarks/...
