dist: trusty
language: cpp
compiler: g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - g++-7
      - gcc-7

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.29.1/bazel_0.29.1-linux-x86_64.deb
  - sha256sum -c utils/bazel_0.29.1-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.29.1-linux-x86_64.deb

script:
  - g++ --version
  - gcc --version
  - sudo rm /usr/bin/g++ # doing this seems like an awful hack, but hey it works.
  - sudo rm /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc
  - g++ --version
  - gcc --version
  - which g++
  - which gcc
  - which g++-7
  - which gcc-7
  - bazel build -s --sandbox_debug --verbose_failures -c opt //benchmarks/...
